server:
  port: 7070

spring:
  application:
    name: "user-account"
  jpa:
    hibernate:
      ddl-auto: "update"
  datasource:
    url: "jdbc:postgresql://localhost:5432/lk_pay"
    username: "lakshay"
    password: "Python043@"
    driver-class-name: "org.postgresql.Driver"